In [3]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [4]:
x = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]], dtype=torch.long, device='mps'
)


y = torch.tensor(
    np.array(
        [[1, 1,1 ],
         [1, 2, 2]], dtype=np.float32
    ), dtype=torch.float32, device='mps'
)

z = x+y
print(z)

tensor([[2., 3., 4.],
        [5., 7., 8.]], device='mps:0')


In [5]:
np_array = np.array([1, 2, 3])
a = torch.from_numpy(np_array)
a

tensor([1, 2, 3])

In [6]:
np_array[0] = 0
a

tensor([0, 2, 3])

In [7]:
b = torch.full((5, 5), torch.pi, dtype=torch.float32, device='mps')
print(b)

tensor([[3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416]], device='mps:0')


In [8]:
c = torch.normal(0, 1, (5, 5))
print(c)

tensor([[ 2.1391, -0.4092,  0.5948, -0.1576, -0.4402],
        [ 1.4976, -0.4704,  1.4702, -0.4696,  0.8382],
        [ 0.3763, -1.5409,  0.8821,  0.3559, -0.7042],
        [-0.6454,  0.4298,  0.9097, -0.2423, -1.1775],
        [-0.5449,  0.8165,  0.2071,  0.1680, -1.7272]])


In [9]:
d = torch.arange(-1, 1, 0.1, device='mps')
print(d)

tensor([-1.0000, -0.9000, -0.8000, -0.7000, -0.6000, -0.5000, -0.4000, -0.3000,
        -0.2000, -0.1000,  0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,
         0.6000,  0.7000,  0.8000,  0.9000], device='mps:0')


In [10]:
f = torch.linspace(-1, 1, 100)
print(f)

tensor([-1.0000, -0.9798, -0.9596, -0.9394, -0.9192, -0.8990, -0.8788, -0.8586,
        -0.8384, -0.8182, -0.7980, -0.7778, -0.7576, -0.7374, -0.7172, -0.6970,
        -0.6768, -0.6566, -0.6364, -0.6162, -0.5960, -0.5758, -0.5556, -0.5354,
        -0.5152, -0.4949, -0.4747, -0.4545, -0.4343, -0.4141, -0.3939, -0.3737,
        -0.3535, -0.3333, -0.3131, -0.2929, -0.2727, -0.2525, -0.2323, -0.2121,
        -0.1919, -0.1717, -0.1515, -0.1313, -0.1111, -0.0909, -0.0707, -0.0505,
        -0.0303, -0.0101,  0.0101,  0.0303,  0.0505,  0.0707,  0.0909,  0.1111,
         0.1313,  0.1515,  0.1717,  0.1919,  0.2121,  0.2323,  0.2525,  0.2727,
         0.2929,  0.3131,  0.3333,  0.3535,  0.3737,  0.3939,  0.4141,  0.4343,
         0.4545,  0.4747,  0.4949,  0.5152,  0.5354,  0.5556,  0.5758,  0.5960,
         0.6162,  0.6364,  0.6566,  0.6768,  0.6970,  0.7172,  0.7374,  0.7576,
         0.7778,  0.7980,  0.8182,  0.8384,  0.8586,  0.8788,  0.8990,  0.9192,
         0.9394,  0.9596,  0.9798,  1.00

In [11]:
g = torch.eye(4, 4, device='mps')
print(g)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], device='mps:0')


In [12]:
w = torch.tensor([1], requires_grad=True, device='mps', dtype=torch.float32)
x = torch.tensor([2],  requires_grad=True, device='mps', dtype=torch.float32)

a = w+x
b = w+1
y = a @ b
y.backward()
print(w.grad)

tensor([5.], device='mps:0')


In [13]:
class OneDimGradTest(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        y = 2.5 * torch.pow(x, 5) + torch.pow(x, 2) + x
        ctx.save_for_backward(x)
        return y

    @staticmethod
    def backward(ctx, grad_output):
        x, = ctx.saved_tensors
        return grad_output * (12.5 * torch.pow(x, 4) + 2*x + 1)

x = torch.tensor([2], requires_grad=True, device='mps', dtype=torch.float)
y = OneDimGradTest.apply(x)
y.backward()
print(x.grad)

tensor([205.], device='mps:0')
